### PR TITLE
QUA-463: Updated base Docker image for plugin 'Sonar PHP'

### PR DESCRIPTION
**Pull request by lucianoruizmo**
## Purpose

Update the base Docker image used in the 'Sonar PHP' plugin.

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Description

To fix the critical vulnerabilities found with Snyk in this repository, we have updated the base Docker image.
The new image is [Amazon Corretto](https://hub.docker.com/_/amazoncorretto), an amazon-maintained image, totally free and up-to-date. The advantages are:
- We can keep using Java 8, no need to update the version.
- We can use a newer version of Alpine (It is possible to use the newest version 3.15, but I think that it's better the previous, more stable version instead)
- It has available an image with the JDK installed.

Adding a screenshot showing the successful docker build + Snyk scan:
image

It was necessary to make some changes in the `build.gradle` field, as I was experiencing this errors:
- I was inconsistently hitting different errors while downloading dependencies (Some times it was Bad Gateway, others it was Time Outs, others just worked fine).
- It was taking a considerable amount of time to build (check the following screenshot where it needed 15 mins to fail, compared to the successful screenshot where it finished in 30 secs)
image

Looking deeper into this, I found [this article](https://blog.gradle.org/jcenter-shutdown) where it says that JCenter (the artifact repository that this project uses) was shutdown on May, 2021. That's the reason why I changed it to use 'Maven Central' instead, improving significantly the build time, with no errors.

EDIT: I've run a local analysis using the CLI and my local image of SonarPHP, and it completed successfully.

image

## Related issues

https://codeclimate.atlassian.net/browse/QUA-463

### CODE REVIEW

**Comment by lucianoruizmo** [comment]
@fede-moya @larkinscott Wow, haven't realised that this repo doesn't have a `config.yaml` for CircleCI. However, the README contains a badge of a successful CircleCI pass, but it just displays the changes on my branch, not any previous build. Do you know how it was being built and deployed before? Should we need to add a config file for this repo?

**Comment by f-moya** [comment]
@lucianoruizmo the Ci config doesn't work because CIrcleCI doesn't support version`1.0` anymore. Can we replicate what Dante has done on https://github.com/codeclimate/codeclimate-coffeelint/pull/35 ? Also, can you also attach a capture of the plugin results using the CLI and the changes that you introduced to the plugin ? Please

**Review by f-moya — COMMENTED** [review]
a little bit worried about changing the repo source but if it runs okay, it's ok for me 👍🏼

**Review by larkinscott — APPROVED** [review]
@lucianoruizmo I wasn't 100% following where we landed in the Slack convo about this, but I agree that if it builds and we're able to confirm locally that it works as expected, I'm a :+1: 

Edit: meant this to just be a comment until we get the circle config in place

**Review by filipesperandio — COMMENTED** [review]
Seems ok to me but would be agree we need a CI working before merging.

Also think it would be nice to try out a base image with a newer jvm version, even if the build target remains java 8, might get us out of some extra trouble in the future if we move pro active have this upgraded. Could be as a follow up PR, but worth spending some time doing it. Recent incidents should teach us that we should not skip on upgrades =\

**Review by f-moya — COMMENTED** [review]
just added new ssh keys to circle ci 👍🏼  it should work now

**Comment by lucianoruizmo** [comment]
@fede-moya @larkinscott @filipesperandio Just requested a re-review from you, now the CI is working.

**Review by larkinscott — APPROVED** [review]
Confirmed all the necessary env vars are set in Circle for releasing the image. LGTM.

**Comment by lucianoruizmo** [comment]
@fede-moya Confirmed that it is reporting issues normally. In this screenshot you can see that the CLI with and without the `--dev` option are reporting the same issue. 
image

(gonna wait until CircleCI issue is fixed before merging)

**Review by f-moya — APPROVED** [review]
nice

**Pull request merged**
